version: "3"
services:
  php:
    container_name: solid_demo
    build:
      context: ./
      dockerfile: "docker/configs/php/Dockerfile"
    environment:
      XDEBUG_CONFIG: "remote_host={{YOUR_IP_ADDRESS}}"
      PHP_IDE_CONFIG: "serverName=docker"
    volumes:
      - ./:/srv/src/solid
